repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/datarootsio/databooks/
    rev: 1.3.8
    hooks:
      - id: databooks-meta
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-pyupgrade
        args: [--py38-plus]
      - id: nbqa-black
      - id: nbqa-isort
        args: [--profile=black]
